### ISSUE TITLE
Cache storm JARs in streaming enrichment

### ISSUE THREAD

**Issue by Alex-Ikanow** [IKANOW/Aleph2#12]
Before rewriting the Storm uber JARs, should check a cache .. need to a) set the cache timestamp to the newest file (and check that), b) generate the name from a hash of the names of the JARs used .. 

..That way when starting/stopping the same job (or creating multiple jobs with the same jars but different configuration) it won't normally have to build the JARs, it can just use whatever files it finds in temp (or could put it in cached-jar like we do for the HDFS caches)

(One issue will be removing the version numbers of aleph2 libs from the hash, to keep the number of hashes tractable - the version numbers don't matter because the timestamp will do that job anyway)

(Also: look into why the JAR builder is so slow, ~1.5MB/s)

**Comment by cburch** [comment]
Pushed some cache changes, ran into some issues w/ the build on travis having different results than running the tests locally, will have to double check on that.

**Comment by cburch** [comment]
TODO: Need to place the cached jars in globals.cached_jars instead of java.io.tmpdir
TODO: Need to clean up unused jars when rpms get upgraded and/or jars go unused?

**Comment by cburch** [comment]
TODO: need to change robs storm jar cleanup cron job to clean up these new jars, which will be in local_cache with the filename "aleph2_storm_jar_*.jar"

**Comment by Alex-Ikanow** [comment]
Doesn't seem to be removing stuff:

```
root@api001 ~]# ls -lrt /opt/aleph2-home/cached-jars/aleph2_storm*
-rw-r--r-- 1 tomcat tomcat  94105930 Aug 24 19:08 /opt/aleph2-home/cached-jars/aleph2_storm_jar_-743376149.jar
-rw-r--r-- 1 tomcat tomcat  94070509 Aug 25 16:13 /opt/aleph2-home/cached-jars/aleph2_storm_jar_1211295179.jar
-rw-r--r-- 1 tomcat tomcat  94147721 Sep  1 12:28 /opt/aleph2-home/cached-jars/aleph2_storm_jar_1147089553.jar
-rw-r--r-- 1 tomcat tomcat  94112573 Sep  1 15:13 /opt/aleph2-home/cached-jars/aleph2_storm_jar_1617870063.jar
```

etc

(Also - not sure if Caleb mentioned but can always delete all the aleph2 storm jars on rpm update ... because they always contain versioned aleph2 lib jars, and the versioning is in the hash)

**Comment by Alex-Ikanow** [comment]
Confirmed
