### ISSUE TITLE
JSON retreived from a source that modifies numeric values to Json Number types should deserialize to the original number type

### ISSUE THREAD

**Issue by rjarrett** [IKANOW/Aleph2#13]
MongoDB currently will take JSON containing an integer {"test":1} and store it with a generic number type. When the object is retrieved, it deserializes to {"test":1.0} which breaks some user applications.

**Comment by Alex-Ikanow** [comment]
I actually think this is done the wrong way round, it should be implemented in the serializer, no? Going to leave this open and think about it....

**Comment by Alex-Ikanow** [comment]
Confirmed by @rjarrett
