### ISSUE TITLE
Elasticsearch Mapping specification does not support non-core types

### ISSUE THREAD

**Issue by rjarrett** [IKANOW/Aleph2#56]
When specifying ES mappings, properties that do not contain "type" in the first level throw back an error that "type" has not been specified. In ES a type of "object" is assumed when "properties" has been specified.

**Comment by Alex-Ikanow** [comment]
Fixed (commit https://github.com/IKANOW/Aleph2-contrib/commit/1ee4bdb302aef34d5a5faa5c01b4fe867af097a6)

confirmed fixed - let me know if I need to backport into the Oct release
