### ISSUE TITLE
Start aleph2 on boot

### ISSUE THREAD

**Issue by robgil** [IKANOW/Aleph2#62]
Aleph2 currently doesnt start on boot or add itself to chkconfig within the aleph2 rpms.

**Comment by Alex-Ikanow** [comment]
Ooh something nasty happened:

It looks like both the old and new JAR files are present when the service is restarted, resulting in 2 versions of a file that has to be unique being present in the classpath:

```
[jar:file:/opt/aleph2-home/lib/aleph2_storm_dependencies-2.5.1535122-debug-shaded.jar!/defaults.yaml, 


jar:file:/opt/aleph2-home/lib/aleph2_storm_dependencies-2.5.1535020-debug-shaded.jar!/defaults.yaml]
```

Not sure what the best way round that is? Just restart if the post if it's an upgrade?

**Comment by Alex-Ikanow** [comment]
Hmm also while I think about it, the restart should only occur if aleph2 is already running, eg it should be something like `service ikanow-aleph2 status && service ikanow-aleph2 restart`

**Comment by Alex-Ikanow** [comment]
Pretty sure we fixed this
