### ISSUE TITLE
Move tmp files to <apphome>/tmp

### ISSUE THREAD

**Issue by robgil** [IKANOW/Aleph2#68]
The following files are being written to the OS /tmp path. Any debugging also goes there and causes the root filesystem to fill up making for a bad time. 
```
# /tmp
1	./aleph2_dedup_test
1	./aleph2_flume_alex_dedup_batch_1_a50430bf7bed
1	./aleph2_flume_alex_netflow_sample_1_1ff894857dac
1	./aleph2_flume_batch_spooldir
1	./aleph2_flume_spooldir
4	./aleph2_testing_test_logstash2__2886dc6f3e56

-rw-r--r--   1 tomcat        tomcat         20G Dec 18 12:59 aleph2_testing_test_logstash2__2886dc6f3e56
```

**Comment by Alex-Ikanow** [comment]
All the app development uses java.io.tmpdir, for files that:
* We don't care if they disappear at random times
* We'd like to be cleared out very intermittently (for general tidiness)

Any directory that satisfies those constraints works also, and can be set with -D

I'd vote to leave it as is for now - the one problem that has been seen was a development/debugging artefact and not part of the production system

**Comment by Alex-Ikanow** [comment]
OK plan is to leave until `/etc/sysconfig/ikanow-aleph2` is in place and then use that to set the tmpdir together with salt config

I'll close this one for now and just add a note in the #67
